### ISSUE TITLE
Can't create plugin serverteleport

### ISSUE THREAD

**Issue by ash-development** [TeamKun/ServerTeleport#1]
```
[06:55:32 ERROR]: Can't create plugin serverteleport
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: NoClassDefFoundError: net/kyori/text/Component
  at ServerTeleport.<init>(ServerTeleport.java:71)
  at VelocityPluginModule.configure(VelocityPluginModule.java:48)
  while locating ServerTeleport

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error
```

**Comment by Bootsjangles** [comment]
Vouch, plugin doesn't work for me either and throws the same error. Does generate it's folder and config however.
